services:
  spine_engine:
    build:
      context: .
      dockerfile: dockerconfig/spine-engine.Dockerfile
    ports:
      - "50001:50001"
    volumes:
      - workdata:/work

  backend:
    build:
      context: .
      dockerfile: dockerconfig/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      WORK_ROOT: /work
      SPINE_ENGINE_HOST: spine_engine
      SPINE_ENGINE_PORT: "50001"
    volumes:
      - workdata:/work
    depends_on:
      - spine_engine

volumes:
  workdata:
