FROM node:22.15-alpine AS builder

WORKDIR /app

COPY siteoptapp/frontend/package*.json ./
RUN npm ci --silent

COPY siteoptapp/frontend/ ./
RUN npm run build


FROM nginx:1.27-alpine

COPY docker/nginx/siteopt-frontend.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]