services:
  backend-prod:
    image: registry.elexia.amct.pl/site_opt/backend-prod:0.2.4
    container_name: backend-prod
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_SECRET_KEY: "verysecret"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend-prod"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost"
      PYTHONUNBUFFERED: "1"
      RUNNING_IN_CONTAINER: "True"
      JULIA_NUM_THREADS: "4"
      OPENBLAS_NUM_THREADS: "1"
      OMP_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      JULIA_JEMALLOC_CONF: "background_thread:true,dirty_decay_ms:1000,muzzy_decay_ms:1000"
      MALLOC_ARENA_MAX: "2"
      REDIS_URL: "redis://redis:6379/1"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_PASSWORD: "change-me"
    volumes:
      - prod_db:/var/lib/siteopt/db
      - prod_work:/app/work_container
      - prod_config:/app/_config
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - docker_network
    depends_on:
      redis:
        condition: service_healthy
    command: >
      bash -lc "
        source /opt/venv/bin/activate &&
        python manage.py migrate &&
        python manage.py create_superuser_if_missing &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 1 --timeout 0 --graceful-timeout 0
      "
    restart: unless-stopped

  frontend-prod:
    image: registry.elexia.amct.pl/site_opt/frontend-prod:0.2.4
    container_name: frontend-prod
    ports:
      - "127.0.0.1:80:80"
    networks:
      - docker_network
    depends_on:
      - backend-prod
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379" # Optional
    networks:
      - docker_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  prod_db: {}
  prod_work: {}
  prod_config: {}

networks:
  docker_network:
    driver: bridge
