services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/siteoptapp/frontend/node_modules
      - /app/siteoptapp/frontend/dist
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=config.settings
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    restart: unless-stopped
