# Generated by Django 5.2 on 2025-05-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DockerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dockerfile", models.CharField(max_length=512)),
                ("docker_run_cmd", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="InputFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fpath", models.CharField(max_length=512)),
                ("display_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="OutputFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fpath", models.CharField(max_length=512)),
                ("display_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("project_dir", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectExecutionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_scenarios", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="InputData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_name", models.CharField(max_length=50)),
                ("nr_input_files", models.IntegerField(default=1)),
                ("input_files", models.ManyToManyField(to="siteoptapp.inputfile")),
            ],
        ),
        migrations.CreateModel(
            name="ExecutionOutputData",
            fields=[
                ("exec_date", models.DateTimeField(verbose_name="date created")),
                (
                    "exec_name",
                    models.CharField(
                        primary_key=True, serialize=False, verbose_name=200
                    ),
                ),
                ("nr_output_files", models.IntegerField(default=1)),
                ("output_files", models.ManyToManyField(to="siteoptapp.outputfile")),
            ],
        ),
    ]
