# Generated by Django 5.2 on 2025-05-12 15:31

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteoptapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executionoutputdata",
            name="output_files",
        ),
        migrations.RenameField(
            model_name="executionoutputdata",
            old_name="exec_date",
            new_name="execution_date",
        ),
        migrations.RemoveField(
            model_name="executionoutputdata",
            name="exec_name",
        ),
        migrations.RemoveField(
            model_name="executionoutputdata",
            name="nr_output_files",
        ),
        migrations.AddField(
            model_name="executionoutputdata",
            name="execution_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="executionoutputdata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="executionoutputdata",
            name="output_archive_basepath",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 5, 12, 15, 31, 34, 760045, tzinfo=datetime.timezone.utc
                ),
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="executionoutputdata",
            name="output_dir",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 5, 12, 15, 31, 49, 476734, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="OutputFile",
        ),
    ]
