# Generated by Django 5.2.5 on 2025-09-05 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteoptapp", "0002_remove_executionoutputdata_output_files_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("config_path", models.TextField()),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
