# Generated by Django 5.2.8 on 2025-12-10 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteoptapp', '0003_clientconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('created_from', models.CharField(default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_folders', to='siteoptapp.clientconfig')),
            ],
            options={
                'unique_together': {('client', 'name')},
            },
        ),
    ]
