"""
Django settings for djangoVue project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path


def env_bool(name: str, default: bool = False) -> bool:
    val = os.getenv(name)
    if val is None:
        return default
    return val.strip().lower() in ("1", "true", "yes", "on")


def _split_csv(name: str, default: str = "") -> list[str]:
    raw = os.getenv(name, default)
    return [x.strip() for x in raw.split(",") if x.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR == '/app' when in container, otherwise it's the repo root
BASE_DIR = Path(__file__).resolve().parent.parent

# Debug
DEBUG = env_bool("DJANGO_DEBUG", default=True)

# Secret
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-9(_#f2mnwmohr%v$xb8d_k6xf&**os=fr2%t)9g)-#!hww=vc&")

ALLOWED_HOSTS = _split_csv("DJANGO_ALLOWED_HOSTS", default="localhost,127.0.0.1")

# Apps
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admindocs",
    "corsheaders",
    "siteoptapp",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# APP_DIRS: True tells the Django template engine to load templates from the
# 'templates' subdirectory inside each installed application
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

if DEBUG:
    # Dev: use in-memory cache
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
else:
    # Production: use Redis
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.getenv("REDIS_URL", "redis://redis:6379/1"),
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Europe/Mariehamn"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# See e.g. STATIC_URL documentation in https://docs.djangoproject.com/en/5.2/ref/settings/#settings-staticfiles
# django.contrib.staticfiles app automatically serves files from the 'static' folder of installed Apps
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # where collectstatic gathers files for production
STATICFILES_DIRS = [BASE_DIR / "siteoptapp/frontend/dist"]  # Path to the Vue.js build directory

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ===== CORS =====
if DEBUG:
    # Dev: allow Vite and localhost variants
    CORS_ALLOWED_ORIGINS = [
        "http://localhost",
        "http://localhost:80",
        "http://localhost:5173",
        "http://localhost:5000",
        "http://127.0.0.1",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:5000",
    ]
else:
    # Prod: prefer explicit env; fall back to ALLOWED_HOSTS as http/https
    explicit = _split_csv("DJANGO_CORS_ALLOWED_ORIGINS")
    if explicit:
        CORS_ALLOWED_ORIGINS = explicit
    else:
        derived = []
        for host in ALLOWED_HOSTS:
            if not host or host == "*":
                continue
            derived.append(f"http://{host}")
            derived.append(f"https://{host}")
        # de-duplicate
        seen = set()
        CORS_ALLOWED_ORIGINS = [x for x in derived if not (x in seen or seen.add(x))]

CORS_ALLOW_CREDENTIALS = True

# ===== CSRF =====
if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost",
        "http://localhost:80",
        "http://localhost:5173",
        "http://localhost:5000",
        "http://127.0.0.1",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:5000",
    ]
else:
    explicit = _split_csv("DJANGO_CSRF_TRUSTED_ORIGINS")
    if explicit:
        CSRF_TRUSTED_ORIGINS = explicit
    else:
        derived = []
        for host in ALLOWED_HOSTS:
            if not host or host == "*":
                continue
            derived.append(f"http://{host}")
            derived.append(f"https://{host}")
        seen = set()
        CSRF_TRUSTED_ORIGINS = [x for x in derived if not (x in seen or seen.add(x))]
CSRF_COOKIE_NAME = "csrftoken"
# For dev with Vite cross-origin fetch, keeping this False is normal.
CSRF_COOKIE_HTTPONLY = False
# In prod behind HTTPS, prefer "Lax" (or "None" if truly cross-site + HTTPS):
CSRF_COOKIE_SAMESITE = "Lax"
# Switch to True when you terminate TLS in front of Django:
CSRF_COOKIE_SECURE = env_bool("DJANGO_USE_HTTPS", default=False)
